### ISSUE TITLE
Local email host gmail requires the allow secure app access to be turn on

### ISSUE THREAD

**Issue by mdshafiquehamid** [anupgupta-arg/Java-BulkMailSenderApp#1]
Just a simple configuration. If we are using gmail.com as the local email host, we have to turn on the less secure app access which will allow us to send an email to the recipient

![image](https://user-images.githubusercontent.com/39638811/64252962-cf126a00-cf4e-11e9-9076-6a67605634bc.png)

**Comment by theRealGupta** [comment]
Yes, because we are going to use Gmail account but not in Gmail app. 
in this application, you are saving your password.
that's why you need to allow from Gmail setting less Secure app is **ON**
